// <auto-generated />
namespace Resume_Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class initialBuild : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialBuild));
        
        string IMigrationMetadata.Id
        {
            get { return "201910170306577_initialBuild"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
